简单线性回归的实现

In [5]:
import numpy as np
def fitSLR(X,y):
    n=len(X)
    dinominator = 0
    numerator = 0
    for i in range(0,n):
        numerator += (X[i] - np.mean(X))*(y[i] - np.mean(y))
        dinominator += (X[i] - np.mean(X))**2
    b1 = numerator/float(dinominator)
    b0 = np.mean(y)- b1*float(np.mean(X))
    return b0,b1
def predict(x,b0,b1):
    return b0 + b1*x

In [6]:
X = [1,3,2,1,3]
y = [14,24,18,17,27]
b0,b1 = fitSLR(X,y)
print("intercept:",b0,"slope:",b1)

intercept: 10.0 slope: 5.0


In [7]:
X_test = 6
y_test = predict(X_test,b0,b1)
print("y_test:",y_test)

y_test: 40.0


多元线性回归,由于矩阵运算的复杂，我们直接使用Sklearn包

In [2]:
from numpy import genfromtxt
from sklearn import datasets, linear_model
dataPath = "Delivery.csv"
deliveryData = genfromtxt(dataPath, delimiter=',')
print ("data:\n",deliveryData)
X = deliveryData[:, :-1]
y = deliveryData[:, -1]
print("X:\n",X,"\ny:\n",y)

data:
 [[100.    4.    9.3]
 [ 50.    3.    4.8]
 [100.    4.    8.9]
 [100.    2.    6.5]
 [ 50.    2.    4.2]
 [ 80.    2.    6.2]
 [ 75.    3.    7.4]
 [ 65.    4.    6. ]
 [ 90.    3.    7.6]
 [ 90.    2.    6.1]]
X:
 [[100.   4.]
 [ 50.   3.]
 [100.   4.]
 [100.   2.]
 [ 50.   2.]
 [ 80.   2.]
 [ 75.   3.]
 [ 65.   4.]
 [ 90.   3.]
 [ 90.   2.]] 
y:
 [9.3 4.8 8.9 6.5 4.2 6.2 7.4 6.  7.6 6.1]


In [3]:
regr =linear_model.LinearRegression()
regr.fit(X,y)
print("coefficients:",regr.coef_)
print("intercept:",regr.intercept_)


coefficients: [0.0611346  0.92342537]
intercept: -0.8687014667817126


In [6]:
xPred = [[102,6]]
yPred = regr.predict(xPred)
print("yPred:",yPred)

yPred: [10.90757981]


数据中存在categories的情况,就是使用00010代替1,00100代替2

In [8]:
filename = "Delivery_Dummy.csv"

datas = genfromtxt(filename,delimiter = ',')

X_data = datas[0:-1,:-1]
Y_data = datas[0:-1,-1]
NLR = linear_model.LinearRegression()
print(X_data,Y_data)

[[100.   4.   0.   1.   0.]
 [ 50.   3.   1.   0.   0.]
 [100.   4.   0.   1.   0.]
 [100.   2.   0.   0.   1.]
 [ 50.   2.   0.   0.   1.]
 [ 80.   2.   0.   1.   0.]
 [ 75.   3.   0.   1.   0.]
 [ 65.   4.   1.   0.   0.]
 [ 90.   3.   1.   0.   0.]] [9.3 4.8 8.9 6.5 4.2 6.2 7.4 6.  7.6]


In [9]:
NLR.fit(X_data,Y_data)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [14]:
pre_test = datas[-1,:-1].reshape(1,5)
print(NLR.predict(pre_test))

[6.18303156]
